NavBar
acm-ucr/ucr-swim-website pull request #50
Opened 2024-04-14 19:55 UTC by shsieh005

<img width="1440" alt="Screenshot 2024-04-14 at 3 41 14 PM" src="https://github.com/acm-ucr/ucr-swim-website/assets/107570820/fa643e16-7e56-4006-af7c-352d574c7199">

2024-04-15 21:18 UTC, seanquiambao requested changes
navigation bar looks great! just a few touch ups

2024-04-15 21:18 UTC, seanquiambao commented on src/components/NavBar.jsx
> +    <div className="px-8 fixed z-30 h-[10vh] bg-white w-screen flex justify-between items-center text-xl">
make the text 2xl, and make the navbar a little bit thinner.

2024-04-16 07:45 UTC, seanquiambao commented
don't forget to link your issues!

2024-04-16 14:43 UTC, shsieh005 commented
<img width="623" alt="image" src="https://github.com/acm-ucr/ucr-swim-website/assets/107570820/917e185e-c77c-4f49-80c0-831011f82a7a">
I got this message in terminal after i tried to push the changes. I git pull origin to try to solve the conflict but it can't be resolved. How can I fix it?

2024-04-16 22:58 UTC, seanquiambao commented
> <img width="623" alt="image" src="https://github.com/acm-ucr/ucr-swim-website/assets/107570820/917e185e-c77c-4f49-80c0-831011f82a7a">
> 
> I got this message in terminal after i tried to push the changes. I git pull origin to try to solve the conflict but it can't be resolved. How can I fix it?

try git pull --rebase

2024-04-17 03:52 UTC, seanquiambao approved these changes

2024-04-17 03:53 UTC, merged