Mobile Responsiveness for Info.jsx and InfoCard.jsx
acm-ucr/ucr-swim-website pull request #83
Opened 2024-04-22 21:21 UTC by kcenzlie

<img width="553" alt="Screenshot 2024-04-22 at 17 20 44" src="https://github.com/acm-ucr/ucr-swim-website/assets/144977959/6876ab02-2cee-498a-911f-598010d34206">

2024-04-23 19:39 UTC, kcenzlie commented
<img width="294" alt="Screenshot 2024-04-23 at 15 30 33" src="https://github.com/acm-ucr/ucr-swim-website/assets/144977959/53c81852-c010-4af1-862e-d8a1506e54e0">

2024-04-23 23:58 UTC, seanquiambao requested changes
is there a way you can unstage the goal.jsx from this pr?

if not then I'll just merge this in and close the other pr.

2024-04-24 02:01 UTC, kcenzlie commented
I'm not really sure how to unstage the goal.jsx from this pull request...

2024-04-24 22:42 UTC, seanquiambao approved these changes

2024-04-24 22:43 UTC, merged